### ISSUE TITLE
Allow incoming broadcast intent

### ISSUE THREAD

**Issue by masahirotanaka** [DeviceConnect/DeviceConnect-Android#125]
We've been modifying the SDK to allow incoming broadcast intent to start and stop the server without a manual operation. However, that introduces a vulnerability that allow any apps installed on the device to control DeviceConnect Manager.

I'd like to open this ticket to discuss how to securely authorize an external app to control server capabilities.

**Comment by masahirotanaka** [comment]
Additionally, we require the app to start a specific activity (like config and plugin page), and they should be added as intent-filter on AndroidManifest.xml. I'd also like to discuss if there are any good idea to do this.

**Comment by masahirotanaka** [comment]
@saysotheara Please follow the conversation.

**Comment by Onuzimoyr** [comment]
Dear Tanaka-san,
Thank you for the issue.
Since it needs to have internal discussion and take some time, we would appreciate you to give us for a while.

Best Regards,

**Comment by Onuzimoyr** [comment]
After internal discussion, we have some concerns and suggestions especially on security issue.

1. Avoiding spoofing by 3rd party app
=> Check to the white list which is registered in MONACA SERVER with origin info which is come from monaca app. mac address, app name and something.
** But please be noted that app name can be added arbitrary code to the app name by 3rd party app, which means app name cannot strictly avoid such spoofing this moment.
=> If your side can agree with this, we can consider on it.

2. User Acceptance
For our side security policy, user should accept manually for use Device Connect Manager.
So need to place a setting page or application page for acceptance (only one time should be enough)

3. Automatically turn off
Since any other plug-ins may be still working, it is very much difficult to turn the manager off by external app automatically at any timing.

Please kindly reconsider on above and we would appreciate you to give us your comment.

**Comment by saysotheara** [comment]
Thank you for the comment. We've agreed with your suggestions regarding security issue.

Also, we'd like to mention several things in response to your points as follows:
1. Normally, when other third party apps want to access certain activities in the DeviceConnect, there should be an option to detect and check which third party app (via packageName) that makes the action. Hence, the DeviceConnect can decide either to allow or reject the action based on the packageName.

2. For the security policy as you concern, user acceptance should be accepted and we are okay with that.

3. Automatically turn off should be okay. However, we were wondering if there is a way to check if plugins are still working inside the DeviceConnect when the action STOP (turn the manager off) was called (either internally or from other third party apps).

**Comment by Onuzimoyr** [comment]
Thank you for the reply with your agreement.
For your comment, I would make some replies as following:

1. We also think so, and besides it may be better to use not only app name (packageName) but also other information like unique ID something so that Device Connect Manager can recognize a contact was certainly come from genuine monaca. It could be achieved by checking with the info managed in monaca server.

2. Thank you for your understanding.

3. Can we have some more detailed scene/usage of stop you image? Originally, we are afraid, don't have clear image on this at this moment. Since monaca should be kept working on background while it is available, so it may not be necessary to shutdown the Device Connect Manager automatically and may be no problem to stop monaca first, then Device Connect Manager individually when the system shutdown.

**Comment by Onuzimoyr** [comment]
Is it possible for us to have any comments on item3 above so that we can have more clear image for it and understand why it needs to be implemented?

Thank you.
Best Regards,

**Comment by saysotheara** [comment]
We have implemented features that are necessary for Monaca to access to DeviceConnect. Please take a look at the pull request to understand what we wish to achieve in DeviceConnect. Please get back to  us should you have any comments.

**Comment by saysotheara** [comment]
Regards the item3, we've understood it clearly that turning off the manager by any change will break the current functionality of the plugin (your concern and also our concern), thus we would like to raise two alternatives as follows:
1. Monaca will never turn off the manager by any change while the plugin is still running unless the users go directly to the DeviceConnect manager and turn it off by themselves.

2. Assuming that the turn off feature is not enabled in Monaca, the users still be able to turn it off in the DeviceConnect app. In this case, we think it would be better if the DC manager app offers  a feature that confirms the running of the plugin and allow the users to know if they really want to turn it off and break the functionality of the plugin.

Thanks,

**Comment by Onuzimoyr** [comment]
For modified implementation, I would comment on some issues in pull-request side.
And for your two suggestions, please see below our comments.

1. Monaca will never turn off the manager by any change while the plugin is still running unless the users go directly to the DeviceConnect manager and turn it off by themselves.

>>> It (manual turn off by users) seems to be no problem because of current operation way of Device Connect Manager. For automatic turn the Manager on, it would be able to do it to make structure of checking Origin as I mentioned above.

2. Assuming that the turn off feature is not enabled in Monaca, the users still be able to turn it off in the DeviceConnect app.
In this case, we think it would be better if the DC manager app offers a feature that confirms the running of the plugin and allow the users to know if they really want to turn it off and break the functionality of the plugin.

>>> In case of showing a dialog, it is able to do that by the Manager side due to security concern.
In case of sending a message to 3rd party app, the Manager doesn't have such functions this moment.

Best Regards,
